// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXehL4s3_lv3VUU0MedkLMKylPW7jxDYk',
    appId: '1:344435057323:web:dec126c1518e4ffc8bcdee',
    messagingSenderId: '344435057323',
    projectId: 'spendguard-7ac04',
    authDomain: 'spendguard-7ac04.firebaseapp.com',
    storageBucket: 'spendguard-7ac04.firebasestorage.app',
    measurementId: 'G-2K2ZYSF10B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiYcW8ksvpIRbE15TquBWhLQ92r6slM4o',
    appId: '1:344435057323:android:09d5d32bfbe760d98bcdee',
    messagingSenderId: '344435057323',
    projectId: 'spendguard-7ac04',
    storageBucket: 'spendguard-7ac04.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnJ0-lMwTzz-U-lAk1wnOB4JMYEK4kssg',
    appId: '1:344435057323:ios:e119928ff61d7b208bcdee',
    messagingSenderId: '344435057323',
    projectId: 'spendguard-7ac04',
    storageBucket: 'spendguard-7ac04.firebasestorage.app',
    iosBundleId: 'com.example.spendguard',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnJ0-lMwTzz-U-lAk1wnOB4JMYEK4kssg',
    appId: '1:344435057323:ios:e119928ff61d7b208bcdee',
    messagingSenderId: '344435057323',
    projectId: 'spendguard-7ac04',
    storageBucket: 'spendguard-7ac04.firebasestorage.app',
    iosBundleId: 'com.example.spendguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXehL4s3_lv3VUU0MedkLMKylPW7jxDYk',
    appId: '1:344435057323:web:dad2d9643843818f8bcdee',
    messagingSenderId: '344435057323',
    projectId: 'spendguard-7ac04',
    authDomain: 'spendguard-7ac04.firebaseapp.com',
    storageBucket: 'spendguard-7ac04.firebasestorage.app',
    measurementId: 'G-F1Q5YNTVXS',
  );
}
